<h1>Instalacja niezbędnych bibliotek</h1>

In [1]:
pip install torch==2.7.0 torchvision==0.22.0 torchaudio==2.7.0 matplotlib numpy

Note: you may need to restart the kernel to use updated packages.


<H1>Import bibliotek</H1>

In [4]:
import torch # główna biblioteka tensorów i obliczeń
import torch.nn as nn # Moduł do budowania sieci neuronowych

<h1>model.train() i model.eval()</h1>

In [6]:
class SimpleModel(nn.Module): # Tworzymy model
    def __init__(self):
        super().__init__() # Wywołujemy konstruktor nn.Module (inicjalizuje wewnętrzne struktury PyTorch, bez tego model nie będzie działał poprawnie)
        self.fc = nn.Linear(4, 4) # Tworzymy warstwę w pełni połączoną, przyjmuje tensor o 4 cechach wejściowych i zwraca 4 wyjściowe
        self.bn = nn.BatchNorm1d(4) # Tworzymy normalizację wsadową dla danych 1D z 4 cechami
        self.dropout = nn.Dropout(p=0.5) # Tworzymy warstwę Droput z prawdopodobieństwem wyzerowania neuronu równym p=0.5 (aktywny tylko w trybie train)

    def forward(self, x): # Definiujemy przepływ danych przez sieć
        x = self.fc(x)    # Linear → BatchNorm → Dropout
        x = self.bn(x)
        x = self.dropout(x)
        return x          # Wynik zwracany jest jako tensor wyjściowy 

model = SimpleModel()   # Tworzymy instancję modelu
x = torch.randn(3, 4)   # Tworzymy tensor wejściowy - batch 3 próbek, każda z 4 cechami
                        # Wartości losowane z z rozkładu normalnego N(0,1)

model.train()              # Przełączamy model w tryb treningowy
output_train_1 = model(x)  # Wywołujemy model 2 razy na tych samych danych
output_train_2 = model(x)  # Wyniki będą różne, bo Dropout za każdym razem losuje inną maskę zerowania neuronów

print("Train mode outputs:")
print(output_train_1)
print(output_train_2)

model.eval()               # Przełączamy model w tryb ewaluacyjny
output_eval_1 = model(x)   # Dwa wywołania na tych samych danych
output_eval_2 = model(x)   # Wyniki będą identyczne (Droput jest wyłączony, BatchNorm używa zapamiętanych statystyk)

print("\nEval mode outputs:")
print(output_eval_1)
print(output_eval_2)

Train mode outputs:
tensor([[ 0.0000,  2.4202,  2.8203,  2.2427],
        [ 1.6270,  0.0000, -1.4657,  0.3708],
        [-0.0000, -0.0000, -0.0000, -2.6136]], grad_fn=<MulBackward0>)
tensor([[ 0.0000,  0.0000,  0.0000,  2.2427],
        [ 0.0000,  0.0569, -0.0000,  0.0000],
        [-0.0000, -0.0000, -0.0000, -2.6136]], grad_fn=<MulBackward0>)

Eval mode outputs:
tensor([[-0.4323, -0.2591,  0.2040,  0.1701],
        [-0.4077, -0.5230,  0.1000, -0.0945],
        [-0.6570, -0.8059,  0.1027, -0.5162]],
       grad_fn=<NativeBatchNormBackward0>)
tensor([[-0.4323, -0.2591,  0.2040,  0.1701],
        [-0.4077, -0.5230,  0.1000, -0.0945],
        [-0.6570, -0.8059,  0.1027, -0.5162]],
       grad_fn=<NativeBatchNormBackward0>)


<h2>Różnice pomiędzy model.train() i model.eval()</h2>
<ul>
    <li style="font-size: 22px;">Dropout
        <ul>
            <li style="font-size: 17px;">train() - aktywny, losowo zeruje neurony z prawdopodobieństwem p</li>
            <li style="font-size: 17px;">eval() - całkowicie wyłączony, dane przechodzą bez żadnych zmian, wynik ejst deterministyczny i powtarzalny</li>
        </ul>
    </li>
    <li style="font-size: 22px;">BatchNorm
        <ul>
            <li style="font-size: 17px;">train() - normalizuje używając statystyk z bieżącego batcha, jednocześnie aktualizuje running_mean i running_var</li>
            <li style="font-size: 17px;">eval() - normalizuje używając zapamiętanych running_mean i running _var, nie aktualizuje ich, nie patrzy na bieżący batch, wynik zależy tylko od tego co model zapamiętał podczas treningu</li>
        </ul>
    </li>
</ul>