<h1>Instalacja niezbędnych bibliotek</h1>

In [17]:
pip install torch==2.10.0 torchvision==0.25.0 torchaudio==2.10.0 --index-url https://download.pytorch.org/whl/cu128 matplotlib numpy

Looking in indexes: https://download.pytorch.org/whl/cu128
  Using cached https://download-r2.pytorch.org/whl/cu128/torch-2.10.0%2Bcu128-cp314-cp314-win_amd64.whl.metadata (29 kB)
  Using cached https://download-r2.pytorch.org/whl/cu128/torchvision-0.25.0%2Bcu128-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
  Using cached https://download-r2.pytorch.org/whl/cu128/torchaudio-2.10.0%2Bcu128-cp314-cp314-win_amd64.whl.metadata (6.8 kB)
   ---------------------------------------- 0.0/2.9 GB ? eta -:--:--
   ---------------------------------------- 0.0/2.9 GB 17.5 MB/s eta 0:02:45
   ---------------------------------------- 0.0/2.9 GB 17.6 MB/s eta 0:02:44
   ---------------------------------------- 0.0/2.9 GB 15.6 MB/s eta 0:03:05
   ---------------------------------------- 0.0/2.9 GB 14.6 MB/s eta 0:03:17
   ---------------------------------------- 0.0/2.9 GB 14.9 MB/s eta 0:03:13
   ---------------------------------------- 0.0/2.9 GB 15.1 MB/s eta 0:03:10
   -------------------------------

ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\gipso\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Users\gipso\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
           ~~~~~~~~~~~~~^^^^^
  File "C:\Users\gipso\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_vendor\urllib3\response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
           ~~~~~~~~~~~~~^^^^^
  File "C:\Users\gipso\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 104, in read
    self.__buf.write(data)
    ~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\gipso\AppData\Local\Python\pythoncore-3.14-64\Lib\tempfile.py", line 520, in func_wrapper
    return func(*args, **kwargs)
OSE

<H1>Import bibliotek</H1>

In [18]:
import torch # główna biblioteka tensorów i obliczeń
import torch.nn as nn # Moduł do budowania sieci neuronowych

<h1>model.train() i model.eval()</h1>

In [20]:
class SimpleModel(nn.Module): # Tworzymy model
    def __init__(self):
        super().__init__() # Wywołujemy konstruktor nn.Module (inicjalizuje wewnętrzne struktury PyTorch, bez tego model nie będzie działał poprawnie)
        self.fc = nn.Linear(4, 4) # Tworzymy warstwę w pełni połączoną, przyjmuje tensor o 4 cechach wejściowych i zwraca 4 wyjściowe
        self.bn = nn.BatchNorm1d(4) # Tworzymy normalizację wsadową dla danych 1D z 4 cechami
        self.dropout = nn.Dropout(p=0.5) # Tworzymy warstwę Droput z prawdopodobieństwem wyzerowania neuronu równym p=0.5 (aktywny tylko w trybie train)

    def forward(self, x): # Definiujemy przepływ danych przez sieć
        x = self.fc(x)    # Linear → BatchNorm → Dropout
        x = self.bn(x)
        x = self.dropout(x)
        return x          # Wynik zwracany jest jako tensor wyjściowy 

model = SimpleModel()   # Tworzymy instancję modelu
x = torch.randn(3, 4)   # Tworzymy tensor wejściowy - batch 3 próbek, każda z 4 cechami
                        # Wartości losowane z z rozkładu normalnego N(0,1)

model.train()              # Przełączamy model w tryb treningowy
output_train_1 = model(x)  # Wywołujemy model 2 razy na tych samych danych
output_train_2 = model(x)  # Wyniki będą różne, bo Dropout za każdym razem losuje inną maskę zerowania neuronów

print("Train mode outputs:")
print(output_train_1)
print(output_train_2)

model.eval()               # Przełączamy model w tryb ewaluacyjny
output_eval_1 = model(x)   # Dwa wywołania na tych samych danych
output_eval_2 = model(x)   # Wyniki będą identyczne (Droput jest wyłączony, BatchNorm używa zapamiętanych statystyk)

print("\nEval mode outputs:")
print(output_eval_1)
print(output_eval_2)

Train mode outputs:
tensor([[ 0.0000,  1.0968,  0.2993,  0.0000],
        [-0.0000,  1.7092, -0.0000,  0.0000],
        [-1.0816, -2.8059,  2.2856, -0.0000]], grad_fn=<MulBackward0>)
tensor([[ 0.0000,  1.0968,  0.2993,  0.2974],
        [-1.7222,  1.7092, -2.5848,  0.0000],
        [-1.0816, -2.8059,  0.0000, -2.5841]], grad_fn=<MulBackward0>)

Eval mode outputs:
tensor([[ 0.8237,  0.2737, -0.3551, -0.6033],
        [ 0.3198,  0.3476, -0.5968, -0.4323],
        [ 0.3912, -0.1975, -0.1887, -0.8510]],
       grad_fn=<NativeBatchNormBackward0>)
tensor([[ 0.8237,  0.2737, -0.3551, -0.6033],
        [ 0.3198,  0.3476, -0.5968, -0.4323],
        [ 0.3912, -0.1975, -0.1887, -0.8510]],
       grad_fn=<NativeBatchNormBackward0>)


<h2>Różnice pomiędzy model.train() i model.eval()</h2>
<ul>
    <li style="font-size: 22px;">Dropout
        <ul>
            <li style="font-size: 17px;">train() - aktywny, losowo zeruje neurony z prawdopodobieństwem p</li>
            <li style="font-size: 17px;">eval() - całkowicie wyłączony, dane przechodzą bez żadnych zmian, wynik ejst deterministyczny i powtarzalny</li>
        </ul>
    </li>
    <li style="font-size: 22px;">BatchNorm
        <ul>
            <li style="font-size: 17px;">train() - normalizuje używając statystyk z bieżącego batcha, jednocześnie aktualizuje running_mean i running_var</li>
            <li style="font-size: 17px;">eval() - normalizuje używając zapamiętanych running_mean i running _var, nie aktualizuje ich, nie patrzy na bieżący batch, wynik zależy tylko od tego co model zapamiętał podczas treningu</li>
        </ul>
    </li>
    <li style="font-size: 22px;">Użycie
        <ul>
            <li style="font-size: 17px;">train() - trenowanie modelu, chcemy, aby Dropout działał oraz BatchNorm aktualizował swoje statystki</li>
            <li style="font-size: 17px;">eval() - walidacja modelu podczas treningu, testowanie na zbiorze testowym, chcemy deterministyczne, powtarzalne wyniki</li>
        </ul>
        </ul>
    </li>
</ul>

<h1>Debugowanie w PyTorch</h1>

In [21]:
x = torch.randn(3, 4) # Tworzymy losowy tensor i sprawdzamy jego właściwości

print(x.shape)   
print(x.dtype)  
print(x.device) 
print(x)

torch.Size([3, 4])
torch.float32
cpu
tensor([[ 0.2484, -1.7158, -1.2018,  1.3965],
        [-1.6521,  0.4544,  0.2012, -2.4093],
        [ 1.7053,  0.6601,  1.0104, -1.2716]])


<h3>Linear</h3>

In [22]:
x = model.fc(x) # nn.Linear(4, 4)

print(x.shape)            
print(x.requires_grad)    
print(x.min().item())     
print(x.max().item())
print(x.mean().item())

torch.Size([3, 4])
True
-1.8092119693756104
1.2167949676513672
0.15791450440883636


<h3>BatchNorm</h3>

In [23]:
x = model.bn(x) # nn.BatchNorm1d(4)

print(x.shape)

print(x.mean(dim=0))
print(x.std(dim=0))

torch.Size([3, 4])
tensor([ 0.7499,  0.2671, -0.1468, -0.0915], grad_fn=<MeanBackward1>)
tensor([0.3392, 0.8024, 1.6819, 0.4040], grad_fn=<StdBackward0>)


<H3>Dropout (train)</H3>

In [24]:
model.train()
x = model.dropout(x)   # p=0.5

print(x.shape)
print(x)

zeros = (x == 0).sum().item()
total = x.numel()
print(f"Wyzerowane: {zeros}/{total} = {zeros/total:.0%}")

torch.Size([3, 4])
tensor([[ 0.8909,  0.0000, -0.0000, -0.0000],
        [ 1.3777, -1.2830,  0.0735, -0.1413],
        [ 0.0000,  0.0000,  2.8715,  0.0000]], grad_fn=<MulBackward0>)
Wyzerowane: 6/12 = 50%


<H3>Dropout (eval)</H3>

In [25]:
model.eval()
x1 = model.dropout(x)
x2 = model.dropout(x)

print("Ilość zer w x1:", (x1 == 0).sum().item())
print("Ilość w x2:", (x2 == 0).sum().item())

print("x1 == x2:", torch.equal(x1, x2))

Ilość zer w x1: 6
Ilość w x2: 6
x1 == x2: True


<h3>Zły rozmiar</h3>

In [26]:
x_wrong = torch.randn(3, 3) # Zły rozmiar - 3 zamiast 4 cech wejściowych

print("shape przed fc:", x_wrong.shape)

try:
    out = model.fc(x_wrong)
except RuntimeError as e:
    print("BŁĄD:", e)

shape przed fc: torch.Size([3, 3])
BŁĄD: mat1 and mat2 shapes cannot be multiplied (3x3 and 4x4)


<h1>state_dict() i zarządzanie stanem modelu w PyTorch</h1>

In [27]:
model = SimpleModel()

# Pełny state_dict
sd = model.state_dict()
print(sd.keys()) # Wyświetlamy co model przechowuje

# Wejście w konkretną warstwę
print(model.fc.weight)         # tensor wag
print(model.fc.weight.shape)   # rozmiar
print(model.fc.bias)           # tensor biasów
print(model.fc.bias.shape)     # rozmiar

# BatchNorm ma dodatkowe statystyki (nie są wagami, ale są w state_dict)
print(model.bn.running_mean)   # zapamiętana średnia
print(model.bn.running_var)    # zapamiętana wariancja
print(model.bn.weight)         # gamma - parametr skali
print(model.bn.bias)           # beta - parametr przesunięcia

odict_keys(['fc.weight', 'fc.bias', 'bn.weight', 'bn.bias', 'bn.running_mean', 'bn.running_var', 'bn.num_batches_tracked'])
Parameter containing:
tensor([[ 0.0302,  0.3851,  0.3062,  0.4962],
        [ 0.3223,  0.4314,  0.4655, -0.4926],
        [-0.2652, -0.2763, -0.4882,  0.4188],
        [ 0.3094,  0.0602, -0.2318,  0.1062]], requires_grad=True)
torch.Size([4, 4])
Parameter containing:
tensor([ 0.3991, -0.0874,  0.2306,  0.2321], requires_grad=True)
torch.Size([4])
tensor([0., 0., 0., 0.])
tensor([1., 1., 1., 1.])
Parameter containing:
tensor([1., 1., 1., 1.], requires_grad=True)
Parameter containing:
tensor([0., 0., 0., 0.], requires_grad=True)


<h3>Edycja wag</h3>

In [28]:
print("Przed:", model.fc.weight)

# Ręczna edycja wag np. zerowanie
with torch.no_grad():
    model.fc.weight.fill_(0.0)
    model.fc.bias.fill_(0.0)

print("Po zerowaniu:", model.fc.weight)

# Edycja poprzez state_dict
sd = model.state_dict()
sd['fc.weight'] = torch.ones(4, 4)
model.load_state_dict(sd)

print("Po load_state_dict:", model.fc.weight)

Przed: Parameter containing:
tensor([[ 0.0302,  0.3851,  0.3062,  0.4962],
        [ 0.3223,  0.4314,  0.4655, -0.4926],
        [-0.2652, -0.2763, -0.4882,  0.4188],
        [ 0.3094,  0.0602, -0.2318,  0.1062]], requires_grad=True)
Po zerowaniu: Parameter containing:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], requires_grad=True)
Po load_state_dict: Parameter containing:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], requires_grad=True)


<h3>Optymalizator</h3>

In [29]:
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

# Robimy jeden krok, aby optymalizator coś zapamiętał
x = torch.randn(3, 4)
loss = model(x).sum()
loss.backward()
optimizer.step()

# Podgląd stanu optymalizatora
opt_sd = optimizer.state_dict()
print(opt_sd['param_groups'])   
print(opt_sd['state'])    

[{'lr': 0.001, 'betas': (0.9, 0.999), 'eps': 1e-08, 'weight_decay': 0, 'amsgrad': False, 'maximize': False, 'foreach': None, 'capturable': False, 'differentiable': False, 'fused': None, 'decoupled_weight_decay': False, 'params': [0, 1, 2, 3]}]
{0: {'step': tensor(1.), 'exp_avg': tensor([[ 0.0166, -0.0281,  0.0803, -0.0688],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0017, -0.0029,  0.0082, -0.0070],
        [-0.0017,  0.0029, -0.0082,  0.0070]]), 'exp_avg_sq': tensor([[2.7701e-05, 7.9215e-05, 6.4540e-04, 4.7383e-04],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [2.8956e-07, 8.2778e-07, 6.7457e-06, 4.9522e-06],
        [2.8957e-07, 8.2778e-07, 6.7457e-06, 4.9522e-06]])}, 1: {'step': tensor(1.), 'exp_avg': tensor([-5.9605e-09,  0.0000e+00, -2.6077e-09, -8.1956e-09]), 'exp_avg_sq': tensor([3.5527e-18, 0.0000e+00, 6.8001e-19, 6.7168e-18])}, 2: {'step': tensor(1.), 'exp_avg': tensor([-0.1615,  0.0000,  0.2818, -0.2818]), 'exp_avg_sq': tensor([0.0026, 0.00

<h3>Zapisywanie i wczytywanie</h3>

In [30]:
# Zalecany sposób, działa bez żadnych flag, zawsze
torch.save(model.state_dict(), 'model.pth') # Zapisujemy na dysk jako plik binarny .pth

# Wczytywanie
model2 = SimpleModel() # Tworzymy nową instancję                           
model2.load_state_dict(torch.load('model.pth'))  # Wczytujemy plik z dysku 
model2.eval() # Przełączamy model w tryb ewaluacyjny

# Niezalecany sposób — zapis całego obiektu modelu
torch.save(model, 'model_full.pth') # Zapisujemy cały obiekt Pythona, plik jest większy i przy wczytaniu musi odtworzyć obiekt klasy, która musi istnieć pod tą samą ścieżką importu
model3 = torch.load('model_full.pth', weights_only=False) # PyTorch odtwarza cały obiekt SimpleModel, klasa musi być zdefiniowana w tym samym miejscu co podczas zapisu

<h3>Checkpointy - zapis pełnego stanu treningu</h3>

In [31]:
# Funkcja do zapisu
def save_checkpoint(model, optimizer, epoch, loss, path):
    torch.save({
        'epoch':                epoch,
        'model_state_dict':     model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'loss':                 loss,
    }, path)
    print(f"Checkpoint zapisany -> {path}")

# Funkcja do odczytu
def load_checkpoint(model, optimizer, path):
    checkpoint = torch.load(path)

    model.load_state_dict(checkpoint['model_state_dict'])
    optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
    epoch = checkpoint['epoch']
    loss = checkpoint['loss']

    print(f"Wznowiono od epoki {epoch}, ostatni loss: {loss:.4f}")
    return epoch, loss

# Użycie w pętli treningowej
model = SimpleModel()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

for epoch in range(100):
    model.train()

    x = torch.randn(3, 4)
    loss = model(x).sum()
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

    # Zapisuj checkpoint co 10 epok
    if epoch % 10 == 0:
        save_checkpoint(model, optimizer, epoch, loss.item(),
                        f'checkpoint_epoch_{epoch}.pth')

# Wznowienie treningu od checkpointu
model = SimpleModel()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
epoch, loss = load_checkpoint(model, optimizer, 'checkpoint_epoch_50.pth')

Checkpoint zapisany -> checkpoint_epoch_0.pth
Checkpoint zapisany -> checkpoint_epoch_10.pth
Checkpoint zapisany -> checkpoint_epoch_20.pth
Checkpoint zapisany -> checkpoint_epoch_30.pth
Checkpoint zapisany -> checkpoint_epoch_40.pth
Checkpoint zapisany -> checkpoint_epoch_50.pth
Checkpoint zapisany -> checkpoint_epoch_60.pth
Checkpoint zapisany -> checkpoint_epoch_70.pth
Checkpoint zapisany -> checkpoint_epoch_80.pth
Checkpoint zapisany -> checkpoint_epoch_90.pth
Wznowiono od epoki 50, ostatni loss: 7.2645
