<h1>Instalacja niezbędnych bibliotek</h1>

In [105]:
pip install torch==2.7.0 torchvision==0.22.0 torchaudio==2.7.0 matplotlib numpy

Note: you may need to restart the kernel to use updated packages.


<H1>Import bibliotek</H1>

In [106]:
import torch # główna biblioteka tensorów i obliczeń
import torch.nn as nn # Moduł do budowania sieci neuronowych

<h1>model.train() i model.eval()</h1>

In [107]:
class SimpleModel(nn.Module): # Tworzymy model
    def __init__(self):
        super().__init__() # Wywołujemy konstruktor nn.Module (inicjalizuje wewnętrzne struktury PyTorch, bez tego model nie będzie działał poprawnie)
        self.fc = nn.Linear(4, 4) # Tworzymy warstwę w pełni połączoną, przyjmuje tensor o 4 cechach wejściowych i zwraca 4 wyjściowe
        self.bn = nn.BatchNorm1d(4) # Tworzymy normalizację wsadową dla danych 1D z 4 cechami
        self.dropout = nn.Dropout(p=0.5) # Tworzymy warstwę Droput z prawdopodobieństwem wyzerowania neuronu równym p=0.5 (aktywny tylko w trybie train)

    def forward(self, x): # Definiujemy przepływ danych przez sieć
        x = self.fc(x)    # Linear → BatchNorm → Dropout
        x = self.bn(x)
        x = self.dropout(x)
        return x          # Wynik zwracany jest jako tensor wyjściowy 

model = SimpleModel()   # Tworzymy instancję modelu
x = torch.randn(3, 4)   # Tworzymy tensor wejściowy - batch 3 próbek, każda z 4 cechami
                        # Wartości losowane z z rozkładu normalnego N(0,1)

model.train()              # Przełączamy model w tryb treningowy
output_train_1 = model(x)  # Wywołujemy model 2 razy na tych samych danych
output_train_2 = model(x)  # Wyniki będą różne, bo Dropout za każdym razem losuje inną maskę zerowania neuronów

print("Train mode outputs:")
print(output_train_1)
print(output_train_2)

model.eval()               # Przełączamy model w tryb ewaluacyjny
output_eval_1 = model(x)   # Dwa wywołania na tych samych danych
output_eval_2 = model(x)   # Wyniki będą identyczne (Droput jest wyłączony, BatchNorm używa zapamiętanych statystyk)

print("\nEval mode outputs:")
print(output_eval_1)
print(output_eval_2)

Train mode outputs:
tensor([[-2.6399, -2.7291,  2.7945,  0.0000],
        [ 0.4407,  0.0000, -1.7746,  0.0000],
        [ 2.1992,  0.0000, -1.0200, -0.0000]], grad_fn=<MulBackward0>)
tensor([[-2.6399, -0.0000,  0.0000,  0.0000],
        [ 0.4407,  0.0000, -1.7746,  0.7336],
        [ 2.1992,  2.0079, -0.0000, -0.0000]], grad_fn=<MulBackward0>)

Eval mode outputs:
tensor([[-0.6296, -1.1837,  0.9624,  0.2860],
        [ 0.3166, -0.0541,  0.1795, -0.1277],
        [ 0.8567,  0.3671,  0.3088, -1.2609]],
       grad_fn=<NativeBatchNormBackward0>)
tensor([[-0.6296, -1.1837,  0.9624,  0.2860],
        [ 0.3166, -0.0541,  0.1795, -0.1277],
        [ 0.8567,  0.3671,  0.3088, -1.2609]],
       grad_fn=<NativeBatchNormBackward0>)


<h2>Różnice pomiędzy model.train() i model.eval()</h2>
<ul>
    <li style="font-size: 22px;">Dropout
        <ul>
            <li style="font-size: 17px;">train() - aktywny, losowo zeruje neurony z prawdopodobieństwem p</li>
            <li style="font-size: 17px;">eval() - całkowicie wyłączony, dane przechodzą bez żadnych zmian, wynik ejst deterministyczny i powtarzalny</li>
        </ul>
    </li>
    <li style="font-size: 22px;">BatchNorm
        <ul>
            <li style="font-size: 17px;">train() - normalizuje używając statystyk z bieżącego batcha, jednocześnie aktualizuje running_mean i running_var</li>
            <li style="font-size: 17px;">eval() - normalizuje używając zapamiętanych running_mean i running _var, nie aktualizuje ich, nie patrzy na bieżący batch, wynik zależy tylko od tego co model zapamiętał podczas treningu</li>
        </ul>
    </li>
    <li style="font-size: 22px;">Użycie
        <ul>
            <li style="font-size: 17px;">train() - trenowanie modelu, chcemy, aby Dropout działał oraz BatchNorm aktualizował swoje statystki</li>
            <li style="font-size: 17px;">eval() - walidacja modelu podczas treningu, testowanie na zbiorze testowym, chcemy deterministyczne, powtarzalne wyniki</li>
        </ul>
        </ul>
    </li>
</ul>

<h1>Debugowanie w PyTorch</h1>

In [108]:
x = torch.randn(3, 4) # Tworzymy losowy tensor i sprawdzamy jego właściwości

print(x.shape)   
print(x.dtype)  
print(x.device) 
print(x)

torch.Size([3, 4])
torch.float32
cpu
tensor([[ 1.5201,  0.5460, -1.6730,  0.2572],
        [ 0.8571,  0.2158,  0.5205,  0.0215],
        [-0.8102, -1.5659,  2.0242,  0.2712]])


<h3>Linear</h3>

In [109]:
x = model.fc(x) # nn.Linear(4, 4)

print(x.shape)            
print(x.requires_grad)    
print(x.min().item())     
print(x.max().item())
print(x.mean().item())

torch.Size([3, 4])
True
-0.7765577435493469
0.8056402206420898
-0.004834393505007029


<h3>BatchNorm</h3>

In [110]:
x = model.bn(x) # nn.BatchNorm1d(4)

print(x.shape)

print(x.mean(dim=0))
print(x.std(dim=0))

torch.Size([3, 4])
tensor([ 0.5542, -0.4774,  0.1842, -0.2639], grad_fn=<MeanBackward1>)
tensor([0.3418, 0.3635, 0.3754, 0.3515], grad_fn=<StdBackward0>)


<H3>Dropout (train)</H3>

In [111]:
model.train()
x = model.dropout(x)   # p=0.5

print(x.shape)
print(x)

zeros = (x == 0).sum().item()
total = x.numel()
print(f"Wyzerowane: {zeros}/{total} = {zeros/total:.0%}")

torch.Size([3, 4])
tensor([[ 1.3897, -0.0000,  0.3025, -1.0951],
        [ 0.0000, -1.4806, -0.0000,  0.0000],
        [ 0.3290, -0.0000,  0.0000, -0.0000]], grad_fn=<MulBackward0>)
Wyzerowane: 7/12 = 58%


<H3>Dropout (eval)</H3>

In [112]:
model.eval()
x1 = model.dropout(x)
x2 = model.dropout(x)

print("Ilość zer w x1:", (x1 == 0).sum().item())
print("Ilość w x2:", (x2 == 0).sum().item())

print("x1 == x2:", torch.equal(x1, x2))

Ilość zer w x1: 7
Ilość w x2: 7
x1 == x2: True


<h3>Zły rozmiar</h3>

In [113]:
x_wrong = torch.randn(3, 3) # Zły rozmiar - 3 zamiast 4 cech wejściowych

print("shape przed fc:", x_wrong.shape)

try:
    out = model.fc(x_wrong)
except RuntimeError as e:
    print("BŁĄD:", e)

shape przed fc: torch.Size([3, 3])
BŁĄD: mat1 and mat2 shapes cannot be multiplied (3x3 and 4x4)


<h1>state_dict() i zarządzanie stanem modelu w PyTorch</h1>

In [119]:
model = SimpleModel()

# Pełny state_dict
sd = model.state_dict()
print(sd.keys()) # Wyświetlamy co model przechowuje

# Wejście w konkretną warstwę
print(model.fc.weight)         # tensor wag
print(model.fc.weight.shape)   # rozmiar
print(model.fc.bias)           # tensor biasów
print(model.fc.bias.shape)     # rozmiar

# BatchNorm ma dodatkowe statystyki (nie są wagami, ale są w state_dict)
print(model.bn.running_mean)   # zapamiętana średnia
print(model.bn.running_var)    # zapamiętana wariancja
print(model.bn.weight)         # gamma - parametr skali
print(model.bn.bias)           # beta - parametr przesunięcia

odict_keys(['fc.weight', 'fc.bias', 'bn.weight', 'bn.bias', 'bn.running_mean', 'bn.running_var', 'bn.num_batches_tracked'])
Parameter containing:
tensor([[-0.4502, -0.1432,  0.2937, -0.4717],
        [ 0.2282,  0.1871, -0.4665,  0.1879],
        [ 0.3174, -0.4796,  0.1705, -0.4718],
        [ 0.1050,  0.0146,  0.4140,  0.0891]], requires_grad=True)
torch.Size([4, 4])
Parameter containing:
tensor([0.4886, 0.1412, 0.3387, 0.0585], requires_grad=True)
torch.Size([4])
tensor([0., 0., 0., 0.])
tensor([1., 1., 1., 1.])
Parameter containing:
tensor([1., 1., 1., 1.], requires_grad=True)
Parameter containing:
tensor([0., 0., 0., 0.], requires_grad=True)


<h3>Edycja wag</h3>

In [115]:
print("Przed:", model.fc.weight)

# Ręczna edycja wag np. zerowanie
with torch.no_grad():
    model.fc.weight.fill_(0.0)
    model.fc.bias.fill_(0.0)

print("Po zerowaniu:", model.fc.weight)

# Edycja poprzez state_dict
sd = model.state_dict()
sd['fc.weight'] = torch.ones(4, 4)
model.load_state_dict(sd)

print("Po load_state_dict:", model.fc.weight)

Przed: Parameter containing:
tensor([[-0.0663, -0.2690, -0.0323, -0.0526],
        [ 0.2677,  0.0043,  0.4944, -0.1121],
        [ 0.0351, -0.1351,  0.3025,  0.2913],
        [-0.1512,  0.2476,  0.0422, -0.3987]], requires_grad=True)
Po zerowaniu: Parameter containing:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], requires_grad=True)
Po load_state_dict: Parameter containing:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], requires_grad=True)


<h3>Optymalizator</h3>

In [116]:
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

# Robimy jeden krok, aby optymalizator coś zapamiętał
x = torch.randn(3, 4)
loss = model(x).sum()
loss.backward()
optimizer.step()

# Podgląd stanu optymalizatora
opt_sd = optimizer.state_dict()
print(opt_sd['param_groups'])   
print(opt_sd['state'])    

[{'lr': 0.001, 'betas': (0.9, 0.999), 'eps': 1e-08, 'weight_decay': 0, 'amsgrad': False, 'maximize': False, 'foreach': None, 'capturable': False, 'differentiable': False, 'fused': None, 'decoupled_weight_decay': False, 'params': [0, 1, 2, 3]}]
{0: {'step': tensor(1.), 'exp_avg': tensor([[ 6.7255e-09, -1.2292e-09, -3.7127e-10,  6.5716e-09],
        [-6.7076e-02,  6.4059e-03,  3.6928e-02,  2.3743e-02],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [-2.9583e-03,  2.8249e-04,  1.6288e-03,  1.0476e-03]]), 'exp_avg_sq': tensor([[4.5233e-18, 1.5109e-19, 1.3784e-20, 4.3186e-18],
        [4.4992e-04, 4.1035e-06, 1.3637e-04, 5.6371e-05],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [8.7513e-07, 7.9800e-09, 2.6531e-07, 1.0975e-07]])}, 1: {'step': tensor(1.), 'exp_avg': tensor([-1.7764e-16, -5.9605e-09,  0.0000e+00, -2.9802e-09]), 'exp_avg_sq': tensor([3.1554e-33, 3.5527e-18, 0.0000e+00, 8.8818e-19])}, 2: {'step': tensor(1.), 'exp_avg': tensor([-1.1697e

<h3>Zapisywanie i wczytywanie</h3>

In [117]:
# Zalecany sposób, działa bez żadnych flag, zawsze
torch.save(model.state_dict(), 'model.pth') # Zapisujemy na dysk jako plik binarny .pth

# Wczytywanie
model2 = SimpleModel() # Tworzymy nową instancję                           
model2.load_state_dict(torch.load('model.pth'))  # Wczytujemy plik z dysku 
model2.eval() # Przełączamy model w tryb ewaluacyjny

# Niezalecany sposób — zapis całego obiektu modelu
torch.save(model, 'model_full.pth') # Zapisujemy cały obiekt Pythona, plik jest większy i przy wczytaniu musi odtworzyć obiekt klasy, która musi istnieć pod tą samą ścieżką importu
model3 = torch.load('model_full.pth', weights_only=False) # PyTorch odtwarza cały obiekt SimpleModel, klasa musi być zdefiniowana w tym samym miejscu co podczas zapisu

<h3>Checkpointy - zapis pełnego stanu treningu</h3>

In [118]:
# Funkcja do zapisu
def save_checkpoint(model, optimizer, epoch, loss, path):
    torch.save({
        'epoch':                epoch,
        'model_state_dict':     model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'loss':                 loss,
    }, path)
    print(f"Checkpoint zapisany -> {path}")

# Funkcja do odczytu
def load_checkpoint(model, optimizer, path):
    checkpoint = torch.load(path)

    model.load_state_dict(checkpoint['model_state_dict'])
    optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
    epoch = checkpoint['epoch']
    loss = checkpoint['loss']

    print(f"Wznowiono od epoki {epoch}, ostatni loss: {loss:.4f}")
    return epoch, loss

# Użycie w pętli treningowej
model = SimpleModel()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

for epoch in range(100):
    model.train()

    x = torch.randn(3, 4)
    loss = model(x).sum()
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

    # Zapisuj checkpoint co 10 epok
    if epoch % 10 == 0:
        save_checkpoint(model, optimizer, epoch, loss.item(),
                        f'checkpoint_epoch_{epoch}.pth')

# Wznowienie treningu od checkpointu
model = SimpleModel()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
epoch, loss = load_checkpoint(model, optimizer, 'checkpoint_epoch_50.pth')

Checkpoint zapisany -> checkpoint_epoch_0.pth
Checkpoint zapisany -> checkpoint_epoch_10.pth
Checkpoint zapisany -> checkpoint_epoch_20.pth
Checkpoint zapisany -> checkpoint_epoch_30.pth
Checkpoint zapisany -> checkpoint_epoch_40.pth
Checkpoint zapisany -> checkpoint_epoch_50.pth
Checkpoint zapisany -> checkpoint_epoch_60.pth
Checkpoint zapisany -> checkpoint_epoch_70.pth
Checkpoint zapisany -> checkpoint_epoch_80.pth
Checkpoint zapisany -> checkpoint_epoch_90.pth
Wznowiono od epoki 50, ostatni loss: 3.5975
