<h1>Instalacja niezbędnych bibliotek</h1>

In [65]:
pip install torch==2.7.0 torchvision==0.22.0 torchaudio==2.7.0 matplotlib numpy

Note: you may need to restart the kernel to use updated packages.


<H1>Import bibliotek</H1>

In [66]:
import torch # główna biblioteka tensorów i obliczeń
import torch.nn as nn # Moduł do budowania sieci neuronowych

<h1>model.train() i model.eval()</h1>

In [67]:
class SimpleModel(nn.Module): # Tworzymy model
    def __init__(self):
        super().__init__() # Wywołujemy konstruktor nn.Module (inicjalizuje wewnętrzne struktury PyTorch, bez tego model nie będzie działał poprawnie)
        self.fc = nn.Linear(4, 4) # Tworzymy warstwę w pełni połączoną, przyjmuje tensor o 4 cechach wejściowych i zwraca 4 wyjściowe
        self.bn = nn.BatchNorm1d(4) # Tworzymy normalizację wsadową dla danych 1D z 4 cechami
        self.dropout = nn.Dropout(p=0.5) # Tworzymy warstwę Droput z prawdopodobieństwem wyzerowania neuronu równym p=0.5 (aktywny tylko w trybie train)

    def forward(self, x): # Definiujemy przepływ danych przez sieć
        x = self.fc(x)    # Linear → BatchNorm → Dropout
        x = self.bn(x)
        x = self.dropout(x)
        return x          # Wynik zwracany jest jako tensor wyjściowy 

model = SimpleModel()   # Tworzymy instancję modelu
x = torch.randn(3, 4)   # Tworzymy tensor wejściowy - batch 3 próbek, każda z 4 cechami
                        # Wartości losowane z z rozkładu normalnego N(0,1)

model.train()              # Przełączamy model w tryb treningowy
output_train_1 = model(x)  # Wywołujemy model 2 razy na tych samych danych
output_train_2 = model(x)  # Wyniki będą różne, bo Dropout za każdym razem losuje inną maskę zerowania neuronów

print("Train mode outputs:")
print(output_train_1)
print(output_train_2)

model.eval()               # Przełączamy model w tryb ewaluacyjny
output_eval_1 = model(x)   # Dwa wywołania na tych samych danych
output_eval_2 = model(x)   # Wyniki będą identyczne (Droput jest wyłączony, BatchNorm używa zapamiętanych statystyk)

print("\nEval mode outputs:")
print(output_eval_1)
print(output_eval_2)

Train mode outputs:
tensor([[ 2.5855,  0.0000, -0.0000,  0.8055],
        [-0.3000, -0.5361,  0.0000, -0.0000],
        [-2.2855, -2.1354, -0.0000,  1.9453]], grad_fn=<MulBackward0>)
tensor([[ 0.0000,  0.0000, -2.3133,  0.0000],
        [-0.0000, -0.0000,  2.5643, -2.7508],
        [-0.0000, -0.0000, -0.2510,  1.9453]], grad_fn=<MulBackward0>)

Eval mode outputs:
tensor([[-0.2231,  0.0595, -0.0998,  0.1984],
        [-0.6478, -0.0955,  0.2008, -1.2598],
        [-0.9400, -0.1728,  0.0273,  0.6658]],
       grad_fn=<NativeBatchNormBackward0>)
tensor([[-0.2231,  0.0595, -0.0998,  0.1984],
        [-0.6478, -0.0955,  0.2008, -1.2598],
        [-0.9400, -0.1728,  0.0273,  0.6658]],
       grad_fn=<NativeBatchNormBackward0>)


<h2>Różnice pomiędzy model.train() i model.eval()</h2>
<ul>
    <li style="font-size: 22px;">Dropout
        <ul>
            <li style="font-size: 17px;">train() - aktywny, losowo zeruje neurony z prawdopodobieństwem p</li>
            <li style="font-size: 17px;">eval() - całkowicie wyłączony, dane przechodzą bez żadnych zmian, wynik ejst deterministyczny i powtarzalny</li>
        </ul>
    </li>
    <li style="font-size: 22px;">BatchNorm
        <ul>
            <li style="font-size: 17px;">train() - normalizuje używając statystyk z bieżącego batcha, jednocześnie aktualizuje running_mean i running_var</li>
            <li style="font-size: 17px;">eval() - normalizuje używając zapamiętanych running_mean i running _var, nie aktualizuje ich, nie patrzy na bieżący batch, wynik zależy tylko od tego co model zapamiętał podczas treningu</li>
        </ul>
    </li>
    <li style="font-size: 22px;">Użycie
        <ul>
            <li style="font-size: 17px;">train() - trenowanie modelu, chcemy, aby Dropout działał oraz BatchNorm aktualizował swoje statystki</li>
            <li style="font-size: 17px;">eval() - walidacja modelu podczas treningu, testowanie na zbiorze testowym, chcemy deterministyczne, powtarzalne wyniki</li>
        </ul>
        </ul>
    </li>
</ul>

<h1>Debugowanie w PyTorch</h1>

In [68]:
x = torch.randn(3, 4) # Tworzymy losowy tensor i sprawdzamy jego właściwości

print(x.shape)   
print(x.dtype)  
print(x.device) 
print(x)

torch.Size([3, 4])
torch.float32
cpu
tensor([[ 1.0697, -0.5900,  1.8419, -1.1509],
        [ 0.3270, -0.3566,  1.2273, -0.2421],
        [-1.0926,  0.3446,  0.9645, -0.9444]])


<h3>Linear</h3>

In [69]:
x = model.fc(x) # nn.Linear(4, 4)

print(x.shape)            
print(x.requires_grad)    
print(x.min().item())     
print(x.max().item())
print(x.mean().item())

torch.Size([3, 4])
True
0.2299719601869583
1.318704605102539
0.6925055384635925


<h3>BatchNorm</h3>

In [70]:
x = model.bn(x) # nn.BatchNorm1d(4)

print(x.shape)

print(x.mean(dim=0))
print(x.std(dim=0))

torch.Size([3, 4])
tensor([0.8723, 0.8472, 0.8466, 0.6131], grad_fn=<MeanBackward1>)
tensor([0.3745, 0.6060, 0.0562, 0.3118], grad_fn=<StdBackward0>)


<H3>Dropout (train)</H3>

In [71]:
model.train()
x = model.dropout(x)   # p=0.5

print(x.shape)
print(x)

zeros = (x == 0).sum().item()
total = x.numel()
print(f"Wyzerowane: {zeros}/{total} = {zeros/total:.0%}")

torch.Size([3, 4])
tensor([[2.6055, 2.9592, 1.7631, 0.5312],
        [0.0000, 1.5811, 1.7528, 0.0000],
        [0.0000, 0.5430, 0.0000, 0.0000]], grad_fn=<MulBackward0>)
Wyzerowane: 5/12 = 42%


<H3>Dropout (eval)</H3>

In [72]:
model.eval()
x1 = model.dropout(x)
x2 = model.dropout(x)

print("Ilość zer w x1:", (x1 == 0).sum().item())
print("Ilość w x2:", (x2 == 0).sum().item())

print("x1 == x2:", torch.equal(x1, x2))

Ilość zer w x1: 5
Ilość w x2: 5
x1 == x2: True


<h3>Zły rozmiar</h3>

In [73]:
x_wrong = torch.randn(3, 3) # Zły rozmiar - 3 zamiast 4 cech wejściowych

print("shape przed fc:", x_wrong.shape)

try:
    out = model.fc(x_wrong)
except RuntimeError as e:
    print("BŁĄD:", e)

shape przed fc: torch.Size([3, 3])
BŁĄD: mat1 and mat2 shapes cannot be multiplied (3x3 and 4x4)
